- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install flake8 pytest coverage
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
- name: Test with coverage
  run: |
    coverage run -m pytest unittests/
    coverage xml
- name: Code Coverage Summary
  uses: irongut/CodeCoverageSummary@v1.3.0
  with:
    filename: coverage.xml
